# Spring
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: aws-sample
  config:
    import: 'aws-parameterstore:'
  security:
    user:
      name: user
      password: password

# Tomcat
server:
  servlet:
    context-path: /aws-sample

aws:
  paramstore:
    enabled: true
    region: ap-northeast-1
    prefix: /config
    profileSeparator: _
    failFast: true